---
title: "경제지표 수집_2021년 01월 작업 기준"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 환경설정 및 데이터 로드
```{r}
library(tidyverse)

library(httr)
library(jsonlite)
library(rvest)
library(XML)
```

```{r}
ecos_api_key <- 'M9X9FH192YCRLP5ZJPDT'
kosis_api_key <- 'NDRjYzg1NGY2MmI1M2ZiOTU1MGU4ZTUzY2M3NWQ4N2Q='

# kosis_stat_nm_tbl_v0 -> v1로 업데이트됨
## - 사유 : K065 table 삭제
#load(file = 'data/kosis/kosis_stat_nm_tbl_v1.RData')
#load(file = "data/ecos/ecos_target_stat_v1.RData")
#ecos_stat_tbl <- ecos_target_stat %>% 
#      filter(RF_YN != "E131") #E131 제외-E130의 실질에 해당


# excel_ref_tbl_v0 -> v1로 업데이트됨
#load(file = 'data/excel_ref_tbl_v0.RData') # 같은 값 처리 

#-------- 월별 변경되는 부분
## 1. KEY Table
#load(file= "data/kosis/kosis_api_key_tbl_202006ver.RData") 
# A tibble: 6,797 x 19
#load(file= "data/ecos/ecos_api_key_tbl_202006ver.RData")
# A tibble: 7,059 x 14
```

# 다음 작업 시 사용할 데이터
```{r}
ecos_api_key <- 'M9X9FH192YCRLP5ZJPDT'
kosis_api_key <- 'NDRjYzg1NGY2MmI1M2ZiOTU1MGU4ZTUzY2M3NWQ4N2Q='

load(file = 'data/kosis/kosis_stat_nm_tbl_v1.RData')
load(file = "data/ecos/ecos_target_stat_v1.RData")

#load(file= "data/kosis/kosis_api_key_tbl_202007ver.RData")
#load(file= "data/kosis/kosis_api_key_tbl_202008ver.RData")
load(file= "data/kosis/kosis_api_key_tbl_202009ver.RData")

#load(file= "data/ecos/ecos_api_key_tbl_202007ver.RData")
#load(file= "data/ecos/ecos_api_key_tbl_202008ver.RData")
load(file= "data/ecos/ecos_api_key_tbl_202009ver.RData")

load(file = 'data/K01_extra_api_key_tbl_202007ver.RData' )

load(file = 'data/excel_ref_tbl_v1.RData')

```


### 변경내용
#### 6월 작업 내용 중
- K065 발주자별 건설수주액(계절조정) 테이블 삭제
  --> 해당 내용 반영함 -> kosis_stat_nm_tbl_v1
- E125 테이블 통계코드 변경됨 (20200623)
  --> 해당 내용 반영함 -> ecos_target_stat_v1


# 사용 함수
## KOSIS
```{r}
'%!in%' <- function(x,y)!('%in%'(x,y))

k_get_date_list <- function(start_date, end_date){
 
  s_year <- start_date %>% str_sub(1, 4) %>% as.numeric()
  s_mon <- start_date %>% str_sub(5, 6) %>% as.numeric()
  e_year <- end_date %>% str_sub(1, 4) %>% as.numeric()
  e_mon <- end_date %>% str_sub(5, 6) %>% as.numeric()
 
  if(s_year == e_year){
   
    date_list <- paste0(s_year, str_pad(s_mon:e_mon, 2, side = "left", pad = 0))
   
    }else if(e_year - s_year == 1){
     
      date_list <- paste0(s_year, str_pad(s_mon:12, 2, side = "left", pad = 0)) %>%
        c(paste0(e_year, str_pad(1:e_mon, 2, side = "left", pad = 0)))
     
      }else{
       
        whole_mon <- NULL
       
        for(y_ind in seq(e_year - s_year - 1)){
         
          whole_mon <- whole_mon %>%
            c(paste0(s_year + y_ind, str_pad(1:12, 2, side = "left", pad = 0)))
         
        }
       
        date_list <- paste0(s_year, str_pad(s_mon:12, 2, side = "left", pad = 0)) %>%
          c(whole_mon) %>%
          c(paste0(e_year, str_pad(1:e_mon, 2, side = "left", pad = 0)))

      }
  return(date_list)
}


k_get_url <- function(api_key, target_date, url){
 
  # api key 변경
  url <- url %>%
    str_replace_all("NDRjYzg1NGY2MmI1M2ZiOTU1MGU4ZTUzY2M3NWQ4N2Q=", api_key)
 
  # 기존 startPrdDe/endPrdDe 위치 잡아서 target_date로 변경
  s_date_lower <- str_locate(url, "&startPrdDe=")[ ,2]
  s_date_upper <- str_locate(url, "&endPrdDe=")[ ,1]
     
  e_date_lower <- str_locate(url, "&endPrdDe=")[ ,2]
  e_date_upper <- str_locate(url, "&loadGubun=")[ ,1]
     
  str_sub(url, start = s_date_lower + 1, end = s_date_upper - 1) <- target_date
  str_sub(url, start = e_date_lower + 1, end = e_date_upper - 1) <- target_date
 
  return(url)
 
}


k_get_api_db_one_mon <- function(api_key, date, stat_id_list){
  
  k_target <- kosis_stat_nm_tbl %>%
    filter(stat_id %in% stat_id_list) %>%
    mutate(url = url %>%
             k_get_url(api_key = api_key, target_date = date))
 
  k_output <- NULL
  for(tbl_ind in seq_along(k_target$url)){
   
    json_temp <- k_target$url[tbl_ind]%>% GET() %>%
      content(as = "text", encoding = "UTF-8")
    
    k_output[[k_target$RF_YN[tbl_ind]]] <-
      tryCatch(fromJSON(txt = json_temp %>% as.character()) %>%
                 as_tibble() %>%
                 spread(key = PRD_DE, value = DT) %>%
                 select(-ends_with("_ENG"), -TBL_NM, -PRD_SE, -ORG_ID),
               error =
                 function(e) {k_output[[k_target$RF_YN[tbl_ind]]] = as_tibble(data.frame("TBL_ID" = "Error", "ITM_NM" = json_temp %>% as.character() %>% str_replace_all('["\a-z{}]', ''), stringsAsFactors=FALSE))})
   
  }

 
  out_tbl <- k_output %>%
    bind_rows(.id="RF_YN")
 
  return(out_tbl)
 
}


kosis_get_api_db <- function(api_key, start_date, end_date, stat_id_list){
 
  time.started <- Sys.time()
  cat(paste('Started at : ', time.started, ' / ...ing...', sep = ''))
 
  date_list <- k_get_date_list(start_date, end_date)
 
  k_api_out <- NULL
  for(mon_ind in seq_along(date_list)){
    k_api_out[[date_list[mon_ind]]] <-
      k_get_api_db_one_mon(api_key, date_list[mon_ind], stat_id_list)
  }
 
  k_api_out_tbl <- k_api_out %>%
    reduce(full_join)
   
  time.finished <- Sys.time() # Store finished time
  time.elapsed  <- time.finished - time.started # Calculate elapsed time
  cat(paste('Finished..! / elapsed time : ', time.elapsed, '\n\n', sep = ''))
 
  return(k_api_out_tbl)

}

```


## ECOS
```{r}
# url입력하면 해당 데이터를 tibble형태로 반환하는 함수
e_convert_xml_to_tbl <- function(api_url){
 
  api_xml <- xmlTreeParse(api_url, useInternalNodes = TRUE) %>%
    xmlRoot()

  output_tbl <- NULL
  for(ind in seq(xmlSize(api_xml))){
   
    if(api_xml[[ind]] %>% xmlSize != 1){
     
      api_item <- xmlSApply(api_xml[[ind]], xmlValue)
     
      obs_line <- api_item %>% t() %>% as_tibble
        data.frame(stringsAsFactors=FALSE)
       
      output_tbl <- output_tbl %>%
        rbind(obs_line)
      }
  }
 
  output_tbl %>% as_tibble()
 
}

# 해당 통계량에 대한 url을 반환하는 함수
e_get_url <- function(stat_code, ecos_api_key, start_date, end_date){
   
    # 2.6. table의 경우 월단위로 변경 필요
    ecos_stat_tbl <- ecos_target_stat %>%  #ecos_target_stat_updated %>%
      mutate(CYCLE = ifelse(STAT_CODE == "098Y001", "MM", CYCLE))  %>%
      filter(RF_YN != "E131")
   
    ecos_base_url <- "http://ecos.bok.or.kr/api/"
    ecos_target <- "StatisticSearch/"#"StatisticItemList/" #"StatisticSearch/"
   
    ecos_sub_url <- "/xml/kr/"
    start_count <- "1"
    end_count <- "30000"
   
    cycle_type <- ecos_stat_tbl[ecos_stat_tbl$STAT_CODE == stat_code, ]$CYCLE
   
    if(cycle_type == "YY"){
     
      start_date <- start_date %>% str_sub(start = 1, end = 4) %>% as.numeric() - 1
      end_date <- end_date %>% str_sub(start = 1, end = 4) %>% as.numeric() - 1
   
    }else if(cycle_type == "QQ"){
     
      start_y <- start_date %>% str_sub(start = 1, end = 4) %>% as.numeric()
      start_m <- start_date %>% str_sub(start = 5, end = 6) %>% as.numeric()
      end_y <- end_date %>% str_sub(start = 1, end = 4) %>% as.numeric()
      end_m <- end_date %>% str_sub(start = 5, end = 6) %>% as.numeric()
     
      if(start_m %in% 1:3){
        start_date <- paste0(start_y - 1, 4)
        }else if(start_m %in% 4:6){
          start_date <- paste0(start_y, 1)
          }else if(start_m %in% 7:9){
            start_date <- paste0(start_y, 2)
            }else{
              start_date <- paste0(start_y, 3)
            }
      if(end_m %in% 1:3){
        end_date <- paste0(end_y - 1, 4)
        }else if(end_m %in% 4:6){
          end_date <- paste0(end_y, 1)
          }else if(end_m %in% 7:9){
            end_date <- paste0(end_y, 2)
            }else{
              end_date <- paste0(end_y, 3)
            }
    }
   
    output_url <- paste0(ecos_base_url,
                   ecos_target,
                   ecos_api_key, ecos_sub_url,
                   start_count, "/", end_count, "/",
                   stat_code,
                   "/", cycle_type, "/",
                   start_date, "/", end_date)
   
    return(output_url)
   
}

# 최종 함수 :
## 사용 함수 : e_get_url, e_convert_xml_to_tbl
ecos_get_api_db <- function(ecos_api_key, start_date, end_date, stat_code_list){
 
  time.started <- Sys.time()
  cat(paste('Started at : ', time.started, ' / ...ing...', sep = ''))
 
  target_stat <- ecos_target_stat %>%
    filter(RF_YN != "E131") %>% 
    filter(STAT_CODE %in% stat_code_list)
 
  output <- NULL
  for(stat_ind in seq_along(target_stat$STAT_CODE)){
    output[[target_stat$RF_YN[stat_ind]]] <-
      tryCatch(target_stat$STAT_CODE[stat_ind] %>%
                 e_get_url(ecos_api_key, start_date, end_date) %>%
                 e_convert_xml_to_tbl() %>%
                 spread(key = TIME, value = DATA_VALUE),
               error = function(e) {output[[target_stat$RF_YN[stat_ind]]] =
                 as_tibble(data.frame("STAT_CODE" = "Error",
                                      stringsAsFactors=FALSE))})
  }
 
  time.finished <- Sys.time() # Store finished time
  time.elapsed  <- time.finished - time.started # Calculate elapsed time
  cat(paste('Finished..! / elapsed time : ', time.elapsed, '\n\n', sep = ''))
 
  output_tbl <- output %>%
    bind_rows(.id = "RF_YN")
 
  return(output_tbl)
 
}

# 6개월 포맷으로 핸들링하기 위한 함수
e_handle_api_db <- function(api_db_tbl){
 
  in_tbl <- api_db_tbl %>%
    left_join(ecos_target_stat %>% select(RF_YN, CYCLE), by = "RF_YN")

  date_vec <- in_tbl %>% select(starts_with("20")) %>% names()

  mon_vec <- date_vec[str_length(date_vec) == "6"]
  year_vec <- date_vec[str_length(date_vec) == "4"]
  quarter_vec <- date_vec[str_length(date_vec) == "5"]
 
  ref_tbl <- data.frame(MM = date_vec[str_length(date_vec) == "6"], stringsAsFactors=FALSE) %>%
    as_tibble() %>%
    mutate(YY = MM %>% str_sub(1, 4) %>% as.numeric() - 1) %>%
    mutate(QQ = ifelse(as.numeric(str_sub(MM, 5, 6)) %in% c(1:3),
                       paste0(MM %>% str_sub(1, 4) %>% as.numeric() - 1, 4),
                       ifelse(as.numeric(str_sub(MM, 5, 6)) %in% c(4:6),
                              paste0(MM %>% str_sub(1, 4), 1),
                              ifelse(as.numeric(str_sub(MM, 5, 6)) %in% c(7:9),
                                     paste0(MM %>% str_sub(1, 4), 2),
                                     ifelse(as.numeric(str_sub(MM, 5, 6)) %in% c(10:12),
                                            paste0(MM %>% str_sub(1, 4), 3), "NON"))))) %>%
    mutate(DB_DATE = MM) %>%
    gather(key = CYCLE, value = API_DATE, MM, YY, QQ)
 
 
  out_tbl <- in_tbl %>% # in_tbl
    gather(key = API_DATE, value = VALUE, date_vec ) %>%  #all_of(date_vec)
    filter(!is.na(VALUE)) %>%
    left_join(ref_tbl,
              by = c("API_DATE", "CYCLE")) %>%
    select(-API_DATE) %>%
    spread(key = DB_DATE, value = VALUE) %>%
    mutate(RF_YN = ifelse(ITEM_NAME1 == "실질" & RF_YN == "E130", "E131", RF_YN))
 
 
  out_tbl[out_tbl$ITEM_CODE2 == " ", ]$ITEM_CODE2 <- NA
  out_tbl[out_tbl$ITEM_CODE3 == " ", ]$ITEM_CODE3 <- NA
 
  start_date <- date_vec[str_length(date_vec) == "6"] %>% as.numeric() %>% min()
  end_date <- date_vec[str_length(date_vec) == "6"] %>% as.numeric() %>% max()
 
 
 
  cat(paste('Finished..! / start date : ', start_date, '\t',
            'end date : ', end_date, sep = ' ', '\n\n'))
 
  return(out_tbl)  
 

}



```



# API DATA 수집 
## KOSIS
```{r}
k_stat_list <- kosis_stat_nm_tbl %>%
  filter(stat_id != "non") %>%
  select(stat_id) %>% unname() %>% as_vector()

kosis_api_db_202006_202011 <- kosis_get_api_db("NDRjYzg1NGY2MmI1M2ZiOTU1MGU4ZTUzY2M3NWQ4N2Q=", start_date = 202006, end_date = 202011, k_stat_list) %>% 
  select(TBL_ID, RF_YN, ITM_NM, ITM_ID, starts_with("C"), starts_with("20")) %>%
  mutate(CYCLE = "MM")

kosis_api_db_202006_202011 %>%
  filter(TBL_ID == "Error") %>% 
  select(ITM_NM)

error_rfyn_202101 <- kosis_api_db_202006_202011 %>%
  filter(TBL_ID == "Error") %>%
  select(RF_YN) %>% unname() %>% as_vector()

kosis_stat_nm_tbl %>%
  filter(RF_YN %in% error_rfyn_202101)


error_stat_id <- kosis_stat_nm_tbl %>%
  filter(RF_YN %in% error_rfyn_202101) %>% select(stat_id) %>% unname() %>% as_vector()

kosis_api_db_202006_202011_sub <- kosis_get_api_db(kosis_api_key, start_date = 202006, end_date = 202010, error_stat_id) #가장 최근월 202006 자료가 없는 것

kosis_api_db_202006_202011_sub %>% filter(TBL_ID == "Error")
# 202005 자료 업데이트 안 됨.. #"K082" "K086" "K089"
# 202006 자료 업데이트 안 됨.. #"K086" "K089"
# 202008 자료 업데이트 안 됨.. #"K086" "K089"
# 202009 자료 업데이트 안 됨.. #"K086" "K089"

#error_stat_id_2 <- kosis_stat_nm_tbl %>%
#  filter(RF_YN %in% c("K086", "K089")) %>%
#  select(stat_id) %>% unname() %>% as_vector()

#kosis_api_db_202006_202011_sub_2 <- kosis_get_api_db(kosis_api_key, start_date = 202006, end_date = 202009, error_stat_id_2) #가장 202008 까지로 한정

#kosis_api_db_202006_202011_sub_2 %>% filter(TBL_ID == "Error")
# Error 없음을 확인

kosis_api_db_202006_202011_vf <- 
  kosis_api_db_202006_202011 %>%
  bind_rows(kosis_api_db_202006_202011_sub) %>%
  #bind_rows(kosis_api_db_202006_202011_sub_2) %>%
  select(TBL_ID, RF_YN, ITM_NM, ITM_ID, starts_with("C"), starts_with("20")) %>%
  mutate(CYCLE = "MM") %>%
  filter(TBL_ID != "Error") %>% 
  distinct()

kosis_api_db_202006_202011_vf # A tibble: 39,135 x 23
# A tibble: 39,142 x 23 : 10월 작업 기준
# A tibble: 39,142 x 23 : 11월 작업 기준
# A tibble: 39,141 x 23 : 11월 작업 기준 

kosis_api_db_202101 <- kosis_api_key_tbl_202009ver %>% 
  select(-ends_with("NM"), -CYCLE) %>% 
  left_join(kosis_api_db_202006_202011_vf %>%
              mutate(C1 = ifelse(RF_YN %in% c("K023", "K091"),
                                 str_pad(C1, side = "left", pad = 0, 4), C1)),
            by = c("RF_YN", "TBL_ID", "C1", "C2", "C3", "C4", "ITM_ID"))

# 매핑 체크
kosis_api_db_202101 %>% 
    filter(is.na(`202006`)) %>% 
  distinct(RF_YN)




kosis_api_db_202101 # 1) KOSIS 기준 OUTPUT 
#A tibble: 6,797 x 25 : 9월 작업기준
#A tibble: 6,797 x 25 : 10월 작업기준
#A tibble: 6,797 x 25 : 11월 작업기준
#A tibble: 6,797 x 25 : 12월 작업기준
#A tibble: 6,797 x 25 : 01월 작업기준

# api key 업데이트 
kosis_api_key_tbl_202101ver <- 
  kosis_api_db_202101 %>% 
  select(-starts_with("20")) 

#save(kosis_api_key_tbl_202009ver,
#    file= "data/kosis/kosis_api_key_tbl_202009ver.RData")



```


## ECOS
```{r}
ecos_api_db_202006_202011 <-
  ecos_get_api_db(ecos_api_key, "202006", "202011", ecos_target_stat$STAT_CODE)


ecos_api_db_202006_202011 %>%
  filter(STAT_CODE == "Error") # Error 확인

# 6개월 형태 테이블로 변경
ecos_api_db_202006_202011_6mon <- e_handle_api_db(ecos_api_db_202006_202011)


# key에 잘 붙는지 체크

ecos_api_key_tbl_202009ver %>% 
  left_join(ecos_api_db_202006_202011_6mon, 
            by = c("RF_YN", "ITEM_CODE1", "ITEM_CODE2", "ITEM_CODE3")) %>%
  filter(is.na(`202006`)) %>%
  filter(!is.na(No.)) %>%
  distinct(RF_YN)  
#  RF_YN
#  <chr>
#1 E006 
#2 E008 
#3 E014 
#4 E017 


null_mapped_chk <- ecos_api_key_tbl_202009ver %>% 
  left_join(ecos_api_db_202006_202011_6mon, 
            by = c("RF_YN", "ITEM_CODE1", "ITEM_CODE2", "ITEM_CODE3")) %>%
  filter(is.na(`202006`)) %>%
  filter(!is.na(No.)) %>%
  distinct(RF_YN) %>% 
  unname() %>% as_vector() 

ecos_api_key_tbl_202009ver %>% 
  left_join(ecos_api_db_202006_202011_6mon, 
            by = c("RF_YN", "ITEM_CODE1", "ITEM_CODE2", "ITEM_CODE3"))  %>% 
  filter(RF_YN %in% null_mapped_chk) %>% select(RF_YN, API_NAME2, starts_with("20")) %>% 
  filter(is.na(`202006`)) 
## A tibble: 9 x 8  -----> skip하기로 함 (09)


ecos_api_db_202101 <- ecos_api_key_tbl_202009ver %>% 
  select(-STAT_CODE, -STAT_NAME, -starts_with("ITEM_NAME"),
         -UNIT_NAME, -CYCLE) %>% 
  left_join(ecos_api_db_202006_202011_6mon, 
            by = c("RF_YN", 
                   "ITEM_CODE1", 
                   "ITEM_CODE2",
                   "ITEM_CODE3"))


ecos_api_db_202101 # 2) ECOS 기준 OUTPUT
# A tibble: 7,059 x 20: 9월 작업기준
# A tibble: 7,059 x 20: 11월 작업기준
# A tibble: 7,059 x 20: 12월 작업기준
# A tibble: 7,059 x 20: 01월 작업기준

#ecos_api_key_tbl_202009ver <- 
#  ecos_api_db_202009 %>% 
#  select(-starts_with("20")) 

#save(ecos_api_key_tbl_202009ver,     file= "data/ecos/ecos_api_key_tbl_202009ver.RData")
```

## API DATA 통합
```{r}
# ecos kosis api 데이터 결합（최종）
ecos_kosis_output_202101 <- ecos_api_db_202101 %>%
  mutate(CYCLE = str_sub(CYCLE, 1, 1)) %>% 
  select(No., RF_YN, ITEM_NAME = ITEM_NAME1, starts_with("20"), SAME_DATA, CYCLE) %>%
  bind_rows(kosis_api_db_202101 %>%
              select(No., RF_YN, ITEM_NAME = ITM_NM, starts_with("20"), SAME_DATA, CYCLE)) #%>%
  
ecos_kosis_output_202101 %>% save(file= "output/ecos_kosis_output_202101.RData")

ecos_kosis_output_202101 # 1) + 2) kosis ecos 통합 API OUTPUT
## A tibble: 13,856 x 11 : 9월 작업기준
## A tibble: 13,856 x 11 : 10월 작업기준
## A tibble: 13,856 x 11 : 11월 작업기준
## A tibble: 13,856 x 11 : 12월 작업기준
## A tibble: 13,861 x 11 : 01월 작업기준
```


# 전처리 
## 같은 값 부여 처리
# 추후에 K065 같은 값 박히는 것 처리해야함

```{r}

#save(excel_ref_tbl, file = 'data/excel_ref_tbl_v1.RData')


obj_tbl <- ecos_kosis_output_202101

# 함수 정의 필요
ecos_kosis_output_202101_excel_ver <- 
  excel_ref_tbl %>% 
  left_join(obj_tbl %>%
              select(-SAME_DATA)) %>% 
  mutate(`202006` = ifelse(SAME_DATA == "T", M201908, `202006`)) %>%
  mutate(`202007` = ifelse(SAME_DATA == "T", M201908, `202007`)) %>%
  mutate(`202008` = ifelse(SAME_DATA == "T", M201908, `202008`)) %>% 
  mutate(`202009` = ifelse(SAME_DATA == "T", M201908, `202009`)) %>% 
  mutate(`202010` = ifelse(SAME_DATA == "T", M201908, `202010`)) %>%
  mutate(`202011` = ifelse(SAME_DATA == "T", M201908, `202011`)) %>%
  select(-M201908) %>% 
  select(`No.`, RF_YN, ITEM_NAME, starts_with("20"), SAME_DATA, CYCLE) %>% 
  mutate_all( funs(ifelse(. %in% c("...", "-"), NA, .)))
  
 

ecos_kosis_output_202101_excel_ver  # 최종 output 
# A tibble: 18,601 x 11
# A tibble: 18,605 x 11 (21.01작업)
length(ecos_kosis_output_202101_excel_ver$No. %>% unique)

ecos_kosis_output_202101_excel_ver[duplicated(ecos_kosis_output_202101_excel_ver$No.),] %>% distinct(RF_YN)
ecos_kosis_output_202101_excel_ver %>% filter(RF_YN == 'K086')

ecos_kosis_output_202101_excel_ver #%>% save(file = "output/ecos_kosis_output_202101_excel_ver.RData")
ecos_kosis_output_202101_excel_ver #%>% write.csv(file = "output/ecos_kosis_output_202011기준.csv", row.names = F, fileEncoding = "cp949")

```




# K01 추가수집
- 018Y301 수입물가지수
- 019Y301 수출물가지수
```{r}

ecos_tbl_extra_import <- 
  ecos_get_api_db(ecos_api_key, "202006", "202011", "018Y301")

ecos_tbl_extra_export <- 
  ecos_get_api_db(ecos_api_key, "202006", "202011", "019Y301")

ecos_tbl_extra <- ecos_tbl_extra_import %>% 
  bind_rows(ecos_tbl_extra_export) %>% 
  filter(ITEM_CODE2 == "W")

```

 

```{r}
#save(K01_extra_api_key_tbl_202007ver, file = 'data/K01_extra_api_key_tbl_202007ver.RData' )
# 다음달부터 얘가 추가 key

K01_extra_api_key_tbl_202007ver %>% 
  left_join(ecos_tbl_extra) %>% 
  filter(is.na(`202006`)) # 매핑 확인

K01_extra_db <- K01_extra_api_key_tbl_202007ver %>% 
  left_join(ecos_tbl_extra)

K01_extra_db %>% write.csv(file = "output/K01_extra_db_202006_202011.csv", row.names = FALSE ,          fileEncoding = "cp949")
```

